# Generated by Django 4.1.5 on 2023-01-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitud', models.FloatField(null=True)),
                ('ancho', models.FloatField(null=True)),
                ('precio', models.FloatField(null=True)),
                ('estado', models.CharField(choices=[('Ocupado', 'Ocupado'), ('Disponible', 'Disponible')], max_length=25, null=True)),
                ('comprador', models.CharField(max_length=25)),
                ('vendedor', models.CharField(max_length=25)),
            ],
        ),
    ]
