# Generated by Django 4.1.5 on 2023-01-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='comprador',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='vendedor',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
