# Generated by Django 4.1.5 on 2023-01-28 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotification', '0005_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='comprador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lotification.clients'),
        ),
    ]
