# Generated by Django 4.1.5 on 2023-01-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotification', '0006_clients_actualizado_alter_lote_comprador'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lote',
            new_name='Lotes',
        ),
    ]
