# Generated by Django 4.1.5 on 2023-01-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotification', '0007_rename_lote_lotes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lotes',
        ),
    ]
