# Generated by Django 4.1.5 on 2023-01-28 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotification', '0009_lot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('numero', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Espacios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('precio', models.FloatField()),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lotification.compradores')),
            ],
        ),
        migrations.RemoveField(
            model_name='lot',
            name='comprador',
        ),
        migrations.DeleteModel(
            name='time_struct',
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Lot',
        ),
    ]
