# Generated by Django 4.1.5 on 2023-01-31 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotification', '0010_compradores_espacios_remove_lot_comprador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=20, null=True)),
                ('client_last_name', models.CharField(max_length=20, null=True)),
                ('client_phone', models.BigIntegerField(null=True)),
                ('client_direction', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot_large', models.FloatField()),
                ('pot_width', models.FloatField()),
                ('pot_price', models.FloatField()),
                ('pot_dispo', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado')], default='Disponible', max_length=20)),
                ('pot_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lotification.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_amount', models.FloatField()),
                ('Payment_date', models.DateField(auto_now_add=True)),
                ('Payment_Pot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lotification.pots')),
            ],
        ),
    ]
