# Generated by Django 4.1.5 on 2023-02-23 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lotification', '0011_clients_pots_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_empl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_emplo_name', models.CharField(max_length=30, null=True)),
                ('user_emplo_last_name', models.CharField(max_length=30, null=True)),
                ('user_emplo_identification', models.CharField(max_length=50, null=True)),
                ('user_emplo_addres', models.TextField(null=True)),
                ('user_emplo_phone', models.BigIntegerField(null=True)),
                ('user_emplo_email', models.CharField(max_length=50, null=True)),
                ('user_user_emplo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
