# Generated by Django 4.1.5 on 2023-02-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotification', '0012_user_empl'),
    ]

    operations = [
        migrations.AddField(
            model_name='pots',
            name='pot_map',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
